# Generated by Django 4.2.4 on 2023-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="비밀번호"),
        ),
    ]
